/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Classification;
 import CGAL.Point_set_3.Point_set_3_Int_iterator; 
public class ETHZ_Random_forest_classifier {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ETHZ_Random_forest_classifier(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ETHZ_Random_forest_classifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_ClassificationJNI.delete_ETHZ_Random_forest_classifier(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ETHZ_Random_forest_classifier(Label_set labels, Feature_set features) {
    this(CGAL_ClassificationJNI.new_ETHZ_Random_forest_classifier(Label_set.getCPtr(labels), labels, Feature_set.getCPtr(features), features), true);
  }

  public void train(Point_set_3_Int_iterator ground_truth, boolean reset_trees, int num_trees, int max_depth) {
    CGAL_ClassificationJNI.ETHZ_Random_forest_classifier_train__SWIG_0(swigCPtr, this, Point_set_3_Int_iterator.getCPtr(ground_truth), ground_truth, reset_trees, num_trees, max_depth);
  }

  public void train(Point_set_3_Int_iterator ground_truth, boolean reset_trees, int num_trees) {
    CGAL_ClassificationJNI.ETHZ_Random_forest_classifier_train__SWIG_1(swigCPtr, this, Point_set_3_Int_iterator.getCPtr(ground_truth), ground_truth, reset_trees, num_trees);
  }

  public void train(Point_set_3_Int_iterator ground_truth, boolean reset_trees) {
    CGAL_ClassificationJNI.ETHZ_Random_forest_classifier_train__SWIG_2(swigCPtr, this, Point_set_3_Int_iterator.getCPtr(ground_truth), ground_truth, reset_trees);
  }

  public void train(Point_set_3_Int_iterator ground_truth) {
    CGAL_ClassificationJNI.ETHZ_Random_forest_classifier_train__SWIG_3(swigCPtr, this, Point_set_3_Int_iterator.getCPtr(ground_truth), ground_truth);
  }

  public void save_configuration(String filename) {
    CGAL_ClassificationJNI.ETHZ_Random_forest_classifier_save_configuration(swigCPtr, this, filename);
  }

  public void load_configuration(String filename) {
    CGAL_ClassificationJNI.ETHZ_Random_forest_classifier_load_configuration(swigCPtr, this, filename);
  }

}
