/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Classification;

public class Feature_set {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Feature_set(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Feature_set obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_ClassificationJNI.delete_Feature_set(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Feature_set() {
    this(CGAL_ClassificationJNI.new_Feature_set(), true);
  }

  public void begin_parallel_additions() {
    CGAL_ClassificationJNI.Feature_set_begin_parallel_additions(swigCPtr, this);
  }

  public void end_parallel_additions() {
    CGAL_ClassificationJNI.Feature_set_end_parallel_additions(swigCPtr, this);
  }

  public void clear() {
    CGAL_ClassificationJNI.Feature_set_clear(swigCPtr, this);
  }

  public int size() {
    return CGAL_ClassificationJNI.Feature_set_size(swigCPtr, this);
  }

  public Feature get(int index) {
    return new Feature(CGAL_ClassificationJNI.Feature_set_get(swigCPtr, this, index), true);
  }

  public boolean remove(Feature feature) {
    return CGAL_ClassificationJNI.Feature_set_remove(swigCPtr, this, Feature.getCPtr(feature), feature);
  }

}
