/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Classification;

public class Feature {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Feature(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Feature obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_ClassificationJNI.delete_Feature(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Feature(SWIGTYPE_p_CGAL_Feature base) {
    this(CGAL_ClassificationJNI.new_Feature(SWIGTYPE_p_CGAL_Feature.getCPtr(base)), true);
  }

  public String name() {
    return CGAL_ClassificationJNI.Feature_name(swigCPtr, this);
  }

  public void set_name(String name) {
    CGAL_ClassificationJNI.Feature_set_name(swigCPtr, this, name);
  }

  public double value(int index) {
    return CGAL_ClassificationJNI.Feature_value(swigCPtr, this, index);
  }

}
