/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Classification;

public class Label {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Label(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Label obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_ClassificationJNI.delete_Label(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Label(SWIGTYPE_p_CGAL_Label base) {
    this(CGAL_ClassificationJNI.new_Label(SWIGTYPE_p_CGAL_Label.getCPtr(base)), true);
  }

  public String name() {
    return CGAL_ClassificationJNI.Label_name(swigCPtr, this);
  }

}
