/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Classification;

public class Point_set_neighbor_query {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Point_set_neighbor_query(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point_set_neighbor_query obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_ClassificationJNI.delete_Point_set_neighbor_query(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point_set_neighbor_query() {
    this(CGAL_ClassificationJNI.new_Point_set_neighbor_query(), true);
  }

}
