/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Classification;

public class Point_set_neighborhood {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Point_set_neighborhood(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point_set_neighborhood obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_ClassificationJNI.delete_Point_set_neighborhood(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point_set_neighborhood(SWIGTYPE_p_CGAL_Point_set_neighborhood base) {
    this(CGAL_ClassificationJNI.new_Point_set_neighborhood(SWIGTYPE_p_CGAL_Point_set_neighborhood.getCPtr(base)), true);
  }

  public Point_set_neighbor_query k_neighbor_query(int k) {
    return new Point_set_neighbor_query(CGAL_ClassificationJNI.Point_set_neighborhood_k_neighbor_query(swigCPtr, this, k), true);
  }

  public Point_set_neighbor_query sphere_neighbor_query(double radius) {
    return new Point_set_neighbor_query(CGAL_ClassificationJNI.Point_set_neighborhood_sphere_neighbor_query(swigCPtr, this, radius), true);
  }

}
