/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Classification;
 import CGAL.Point_set_3.Point_set_3; import CGAL.Point_set_3.Point_set_3_Vector_map; import CGAL.Point_set_3.Point_set_3_Int_map; 
public class Point_set_feature_generator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Point_set_feature_generator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point_set_feature_generator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_ClassificationJNI.delete_Point_set_feature_generator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point_set_feature_generator(Point_set_3 point_set, int nb_scales, double voxel_size) {
    this(CGAL_ClassificationJNI.new_Point_set_feature_generator__SWIG_0(Point_set_3.getCPtr(point_set), point_set, nb_scales, voxel_size), true);
  }

  public Point_set_feature_generator(Point_set_3 point_set, int nb_scales) {
    this(CGAL_ClassificationJNI.new_Point_set_feature_generator__SWIG_1(Point_set_3.getCPtr(point_set), point_set, nb_scales), true);
  }

  public void generate_point_based_features(Feature_set features) {
    CGAL_ClassificationJNI.Point_set_feature_generator_generate_point_based_features(swigCPtr, this, Feature_set.getCPtr(features), features);
  }

  public void generate_normal_based_features(Feature_set features, Point_set_3_Vector_map normal_map) {
    CGAL_ClassificationJNI.Point_set_feature_generator_generate_normal_based_features(swigCPtr, this, Feature_set.getCPtr(features), features, Point_set_3_Vector_map.getCPtr(normal_map), normal_map);
  }

  public void generate_color_based_features(Feature_set features, Point_set_3_Int_map red_map, Point_set_3_Int_map green_map, Point_set_3_Int_map blue_map) {
    CGAL_ClassificationJNI.Point_set_feature_generator_generate_color_based_features(swigCPtr, this, Feature_set.getCPtr(features), features, Point_set_3_Int_map.getCPtr(red_map), red_map, Point_set_3_Int_map.getCPtr(green_map), green_map, Point_set_3_Int_map.getCPtr(blue_map), blue_map);
  }

  public void generate_echo_based_features(Feature_set features, Point_set_3_Int_map echo_map) {
    CGAL_ClassificationJNI.Point_set_feature_generator_generate_echo_based_features(swigCPtr, this, Feature_set.getCPtr(features), features, Point_set_3_Int_map.getCPtr(echo_map), echo_map);
  }

  public Point_set_neighborhood neighborhood(int scale) {
    return new Point_set_neighborhood(CGAL_ClassificationJNI.Point_set_feature_generator_neighborhood__SWIG_0(swigCPtr, this, scale), true);
  }

  public Point_set_neighborhood neighborhood() {
    return new Point_set_neighborhood(CGAL_ClassificationJNI.Point_set_feature_generator_neighborhood__SWIG_1(swigCPtr, this), true);
  }

  public int number_of_scales() {
    return CGAL_ClassificationJNI.Point_set_feature_generator_number_of_scales(swigCPtr, this);
  }

  public double grid_resolution(int c) {
    return CGAL_ClassificationJNI.Point_set_feature_generator_grid_resolution(swigCPtr, this, c);
  }

  public double radius_neighbors(int c) {
    return CGAL_ClassificationJNI.Point_set_feature_generator_radius_neighbors(swigCPtr, this, c);
  }

  public double radius_dtm(int c) {
    return CGAL_ClassificationJNI.Point_set_feature_generator_radius_dtm(swigCPtr, this, c);
  }

}
