/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Classification;

public class SWIGTYPE_p_CGAL_Point_set_neighborhood {
  private transient long swigCPtr;

  public SWIGTYPE_p_CGAL_Point_set_neighborhood(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_p_CGAL_Point_set_neighborhood() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_CGAL_Point_set_neighborhood obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

