/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Triangulation_2;

public interface CGAL_Triangulation_2Constants {
  public final static int CGAL_VERSION_NR = 1050031000;
  public final static int CGAL_SVN_REVISION = 99999;
  public final static int CGAL_RELEASE_DATE = 20200801;
}
