/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Shape_detection;

import CGAL.Kernel.Point_3;
import CGAL.Kernel.Vector_3;
import CGAL.Point_set_3.Point_set_3;
import CGAL.Point_set_3.Point_set_3_Int_map;
import java.util.Iterator;
import java.util.Collection;

public class CGAL_Shape_detectionJNI {

    static {
      try {
          System.loadLibrary("CGAL_Shape_detection");
      } catch (UnsatisfiedLinkError e) {
        System.err.println("Native code library CGAL_Shape_detection failed to load. \n" + e);
        throw e;
      }
    }
  

    static{
      try {
          System.loadLibrary("CGAL_Java");
      } catch (UnsatisfiedLinkError e) {
        System.err.println("Native code library CGAL_Java failed to load. \n" + e);
        throw e;
      }
    }
  
  public final static native int region_growing__SWIG_0(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5, double jarg6, int jarg7);
  public final static native int region_growing__SWIG_1(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5, double jarg6);
  public final static native int region_growing__SWIG_2(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5);
  public final static native int region_growing__SWIG_3(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4);
  public final static native int region_growing__SWIG_4(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3);
  public final static native int region_growing__SWIG_5(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_);
  public final static native String[] efficient_RANSAC__SWIG_0(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5, double jarg6, double jarg7, boolean jarg8, boolean jarg9, boolean jarg10, boolean jarg11, boolean jarg12);
  public final static native String[] efficient_RANSAC__SWIG_1(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5, double jarg6, double jarg7, boolean jarg8, boolean jarg9, boolean jarg10, boolean jarg11);
  public final static native String[] efficient_RANSAC__SWIG_2(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5, double jarg6, double jarg7, boolean jarg8, boolean jarg9, boolean jarg10);
  public final static native String[] efficient_RANSAC__SWIG_3(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5, double jarg6, double jarg7, boolean jarg8, boolean jarg9);
  public final static native String[] efficient_RANSAC__SWIG_4(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5, double jarg6, double jarg7, boolean jarg8);
  public final static native String[] efficient_RANSAC__SWIG_5(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5, double jarg6, double jarg7);
  public final static native String[] efficient_RANSAC__SWIG_6(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5, double jarg6);
  public final static native String[] efficient_RANSAC__SWIG_7(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4, double jarg5);
  public final static native String[] efficient_RANSAC__SWIG_8(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3, double jarg4);
  public final static native String[] efficient_RANSAC__SWIG_9(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_, int jarg3);
  public final static native String[] efficient_RANSAC__SWIG_10(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_);
}
