/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Point_set_3;

import CGAL.Kernel.Point_3;
import CGAL.Kernel.Vector_3;
import java.util.Iterator;
import java.util.Collection;

public class CGAL_Point_set_3JNI {

    static {
      try {
          System.loadLibrary("CGAL_Point_set_3");
      } catch (UnsatisfiedLinkError e) {
        System.err.println("Native code library CGAL_Point_set_3 failed to load. \n" + e);
        throw e;
      }
    }
  

    static{
      try {
          System.loadLibrary("CGAL_Java");
      } catch (UnsatisfiedLinkError e) {
        System.err.println("Native code library CGAL_Java failed to load. \n" + e);
        throw e;
      }
    }
  
  public final static native long new_Point_set_3__SWIG_0(boolean jarg1);
  public final static native long new_Point_set_3__SWIG_1();
  public final static native long new_Point_set_3__SWIG_2(String jarg1);
  public final static native boolean Point_set_3_is_empty(long jarg1, Point_set_3 jarg1_);
  public final static native boolean Point_set_3_empty(long jarg1, Point_set_3 jarg1_);
  public final static native int Point_set_3_number_of_points(long jarg1, Point_set_3 jarg1_);
  public final static native int Point_set_3_size(long jarg1, Point_set_3 jarg1_);
  public final static native boolean Point_set_3_join(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3 jarg2_);
  public final static native void Point_set_3_clear(long jarg1, Point_set_3 jarg1_);
  public final static native void Point_set_3_clear_properties(long jarg1, Point_set_3 jarg1_);
  public final static native void Point_set_3_reserve(long jarg1, Point_set_3 jarg1_, int jarg2);
  public final static native void Point_set_3_resize(long jarg1, Point_set_3 jarg1_, int jarg2);
  public final static native int Point_set_3_insert__SWIG_0(long jarg1, Point_set_3 jarg1_);
  public final static native int Point_set_3_insert__SWIG_1(long jarg1, Point_set_3 jarg1_, long jarg2, Point_3 jarg2_);
  public final static native int Point_set_3_insert__SWIG_2(long jarg1, Point_set_3 jarg1_, long jarg2, Point_3 jarg2_, long jarg3, Vector_3 jarg3_);
  public final static native int Point_set_3_insert__SWIG_3(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3 jarg2_, int jarg3);
  public final static native void Point_set_3_insert_range(long jarg1, Point_set_3 jarg1_, double[] jarg2);
  public final static native long Point_set_3_indices(long jarg1, Point_set_3 jarg1_);
  public final static native long Point_set_3_point(long jarg1, Point_set_3 jarg1_, int jarg2);
  public final static native long Point_set_3_normal(long jarg1, Point_set_3 jarg1_, int jarg2);
  public final static native void Point_set_3_remove(long jarg1, Point_set_3 jarg1_, int jarg2);
  public final static native boolean Point_set_3_is_removed(long jarg1, Point_set_3 jarg1_, int jarg2);
  public final static native long Point_set_3_garbage(long jarg1, Point_set_3 jarg1_);
  public final static native int Point_set_3_number_of_removed_points(long jarg1, Point_set_3 jarg1_);
  public final static native int Point_set_3_garbage_size(long jarg1, Point_set_3 jarg1_);
  public final static native boolean Point_set_3_has_garbage(long jarg1, Point_set_3 jarg1_);
  public final static native void Point_set_3_collect_garbage(long jarg1, Point_set_3 jarg1_);
  public final static native void Point_set_3_cancel_removals(long jarg1, Point_set_3 jarg1_);
  public final static native boolean Point_set_3_has_int_map(long jarg1, Point_set_3 jarg1_, String jarg2);
  public final static native long Point_set_3_add_int_map__SWIG_0(long jarg1, Point_set_3 jarg1_, String jarg2, int jarg3);
  public final static native long Point_set_3_add_int_map__SWIG_1(long jarg1, Point_set_3 jarg1_, String jarg2);
  public final static native long Point_set_3_int_map(long jarg1, Point_set_3 jarg1_, String jarg2);
  public final static native boolean Point_set_3_remove_int_map(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_);
  public final static native boolean Point_set_3_has_float_map(long jarg1, Point_set_3 jarg1_, String jarg2);
  public final static native long Point_set_3_add_float_map__SWIG_0(long jarg1, Point_set_3 jarg1_, String jarg2, double jarg3);
  public final static native long Point_set_3_add_float_map__SWIG_1(long jarg1, Point_set_3 jarg1_, String jarg2);
  public final static native long Point_set_3_float_map(long jarg1, Point_set_3 jarg1_, String jarg2);
  public final static native boolean Point_set_3_remove_float_map(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Float_map jarg2_);
  public final static native boolean Point_set_3_has_normal_map(long jarg1, Point_set_3 jarg1_);
  public final static native long Point_set_3_add_normal_map(long jarg1, Point_set_3 jarg1_);
  public final static native long Point_set_3_normal_map(long jarg1, Point_set_3 jarg1_);
  public final static native boolean Point_set_3_remove_normal_map(long jarg1, Point_set_3 jarg1_);
  public final static native long Point_set_3_point_map(long jarg1, Point_set_3 jarg1_);
  public final static native void Point_set_3_copy_properties(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3 jarg2_);
  public final static native String[] Point_set_3_properties(long jarg1, Point_set_3 jarg1_);
  public final static native String Point_set_3_info(long jarg1, Point_set_3 jarg1_);
  public final static native long Point_set_3_range__SWIG_0(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Int_map jarg2_);
  public final static native long Point_set_3_range__SWIG_1(long jarg1, Point_set_3 jarg1_, long jarg2, Point_set_3_Float_map jarg2_);
  public final static native long Point_set_3_points(long jarg1, Point_set_3 jarg1_);
  public final static native long Point_set_3_normals(long jarg1, Point_set_3 jarg1_);
  public final static native void Point_set_3_read(long jarg1, Point_set_3 jarg1_, String jarg2);
  public final static native boolean Point_set_3_write(long jarg1, Point_set_3 jarg1_, String jarg2);
  public final static native void delete_Point_set_3(long jarg1);
  public final static native long new_Point_set_3_iterator();
  public final static native int Point_set_3_iterator_slow_next(long jarg1, Point_set_3_iterator jarg1_);
  public final static native void Point_set_3_iterator_next(long jarg1, Point_set_3_iterator jarg1_, long jarg2);
  public final static native long Point_set_3_iterator_clone__SWIG_0(long jarg1, Point_set_3_iterator jarg1_);
  public final static native void Point_set_3_iterator_clone__SWIG_1(long jarg1, Point_set_3_iterator jarg1_, long jarg2, Point_set_3_iterator jarg2_);
  public final static native boolean Point_set_3_iterator_hasNext(long jarg1, Point_set_3_iterator jarg1_);
  public final static native boolean Point_set_3_iterator_equals(long jarg1, Point_set_3_iterator jarg1_, long jarg2, Point_set_3_iterator jarg2_);
  public final static native boolean Point_set_3_iterator_not_equals(long jarg1, Point_set_3_iterator jarg1_, long jarg2, Point_set_3_iterator jarg2_);
  public final static native void delete_Point_set_3_iterator(long jarg1);
  public final static native long new_Point_set_3_Point_iterator();
  public final static native long Point_set_3_Point_iterator_slow_next(long jarg1, Point_set_3_Point_iterator jarg1_);
  public final static native void Point_set_3_Point_iterator_next(long jarg1, Point_set_3_Point_iterator jarg1_, long jarg2, Point_3 jarg2_);
  public final static native long Point_set_3_Point_iterator_clone__SWIG_0(long jarg1, Point_set_3_Point_iterator jarg1_);
  public final static native void Point_set_3_Point_iterator_clone__SWIG_1(long jarg1, Point_set_3_Point_iterator jarg1_, long jarg2, Point_set_3_Point_iterator jarg2_);
  public final static native boolean Point_set_3_Point_iterator_hasNext(long jarg1, Point_set_3_Point_iterator jarg1_);
  public final static native boolean Point_set_3_Point_iterator_equals(long jarg1, Point_set_3_Point_iterator jarg1_, long jarg2, Point_set_3_Point_iterator jarg2_);
  public final static native boolean Point_set_3_Point_iterator_not_equals(long jarg1, Point_set_3_Point_iterator jarg1_, long jarg2, Point_set_3_Point_iterator jarg2_);
  public final static native void delete_Point_set_3_Point_iterator(long jarg1);
  public final static native long new_Point_set_3_Vector_iterator();
  public final static native long Point_set_3_Vector_iterator_slow_next(long jarg1, Point_set_3_Vector_iterator jarg1_);
  public final static native void Point_set_3_Vector_iterator_next(long jarg1, Point_set_3_Vector_iterator jarg1_, long jarg2, Vector_3 jarg2_);
  public final static native long Point_set_3_Vector_iterator_clone__SWIG_0(long jarg1, Point_set_3_Vector_iterator jarg1_);
  public final static native void Point_set_3_Vector_iterator_clone__SWIG_1(long jarg1, Point_set_3_Vector_iterator jarg1_, long jarg2, Point_set_3_Vector_iterator jarg2_);
  public final static native boolean Point_set_3_Vector_iterator_hasNext(long jarg1, Point_set_3_Vector_iterator jarg1_);
  public final static native boolean Point_set_3_Vector_iterator_equals(long jarg1, Point_set_3_Vector_iterator jarg1_, long jarg2, Point_set_3_Vector_iterator jarg2_);
  public final static native boolean Point_set_3_Vector_iterator_not_equals(long jarg1, Point_set_3_Vector_iterator jarg1_, long jarg2, Point_set_3_Vector_iterator jarg2_);
  public final static native void delete_Point_set_3_Vector_iterator(long jarg1);
  public final static native long new_Point_set_3_Int_iterator();
  public final static native int Point_set_3_Int_iterator_slow_next(long jarg1, Point_set_3_Int_iterator jarg1_);
  public final static native void Point_set_3_Int_iterator_next(long jarg1, Point_set_3_Int_iterator jarg1_, long jarg2);
  public final static native long Point_set_3_Int_iterator_clone__SWIG_0(long jarg1, Point_set_3_Int_iterator jarg1_);
  public final static native void Point_set_3_Int_iterator_clone__SWIG_1(long jarg1, Point_set_3_Int_iterator jarg1_, long jarg2, Point_set_3_Int_iterator jarg2_);
  public final static native boolean Point_set_3_Int_iterator_hasNext(long jarg1, Point_set_3_Int_iterator jarg1_);
  public final static native boolean Point_set_3_Int_iterator_equals(long jarg1, Point_set_3_Int_iterator jarg1_, long jarg2, Point_set_3_Int_iterator jarg2_);
  public final static native boolean Point_set_3_Int_iterator_not_equals(long jarg1, Point_set_3_Int_iterator jarg1_, long jarg2, Point_set_3_Int_iterator jarg2_);
  public final static native void delete_Point_set_3_Int_iterator(long jarg1);
  public final static native long new_Point_set_3_Float_iterator();
  public final static native double Point_set_3_Float_iterator_slow_next(long jarg1, Point_set_3_Float_iterator jarg1_);
  public final static native void Point_set_3_Float_iterator_next(long jarg1, Point_set_3_Float_iterator jarg1_, long jarg2);
  public final static native long Point_set_3_Float_iterator_clone__SWIG_0(long jarg1, Point_set_3_Float_iterator jarg1_);
  public final static native void Point_set_3_Float_iterator_clone__SWIG_1(long jarg1, Point_set_3_Float_iterator jarg1_, long jarg2, Point_set_3_Float_iterator jarg2_);
  public final static native boolean Point_set_3_Float_iterator_hasNext(long jarg1, Point_set_3_Float_iterator jarg1_);
  public final static native boolean Point_set_3_Float_iterator_equals(long jarg1, Point_set_3_Float_iterator jarg1_, long jarg2, Point_set_3_Float_iterator jarg2_);
  public final static native boolean Point_set_3_Float_iterator_not_equals(long jarg1, Point_set_3_Float_iterator jarg1_, long jarg2, Point_set_3_Float_iterator jarg2_);
  public final static native void delete_Point_set_3_Float_iterator(long jarg1);
  public final static native long new_Point_set_3_Point_map();
  public final static native long Point_set_3_Point_map_get(long jarg1, Point_set_3_Point_map jarg1_, int jarg2);
  public final static native void Point_set_3_Point_map_set(long jarg1, Point_set_3_Point_map jarg1_, int jarg2, long jarg3, Point_3 jarg3_);
  public final static native boolean Point_set_3_Point_map_is_valid(long jarg1, Point_set_3_Point_map jarg1_);
  public final static native long Point_set_3_Point_map_clone__SWIG_0(long jarg1, Point_set_3_Point_map jarg1_);
  public final static native void Point_set_3_Point_map_clone__SWIG_1(long jarg1, Point_set_3_Point_map jarg1_, long jarg2, Point_set_3_Point_map jarg2_);
  public final static native void delete_Point_set_3_Point_map(long jarg1);
  public final static native long new_Point_set_3_Vector_map();
  public final static native long Point_set_3_Vector_map_get(long jarg1, Point_set_3_Vector_map jarg1_, int jarg2);
  public final static native void Point_set_3_Vector_map_set(long jarg1, Point_set_3_Vector_map jarg1_, int jarg2, long jarg3, Vector_3 jarg3_);
  public final static native boolean Point_set_3_Vector_map_is_valid(long jarg1, Point_set_3_Vector_map jarg1_);
  public final static native long Point_set_3_Vector_map_clone__SWIG_0(long jarg1, Point_set_3_Vector_map jarg1_);
  public final static native void Point_set_3_Vector_map_clone__SWIG_1(long jarg1, Point_set_3_Vector_map jarg1_, long jarg2, Point_set_3_Vector_map jarg2_);
  public final static native void delete_Point_set_3_Vector_map(long jarg1);
  public final static native long new_Point_set_3_Int_map();
  public final static native int Point_set_3_Int_map_get(long jarg1, Point_set_3_Int_map jarg1_, int jarg2);
  public final static native void Point_set_3_Int_map_set(long jarg1, Point_set_3_Int_map jarg1_, int jarg2, int jarg3);
  public final static native boolean Point_set_3_Int_map_is_valid(long jarg1, Point_set_3_Int_map jarg1_);
  public final static native long Point_set_3_Int_map_clone__SWIG_0(long jarg1, Point_set_3_Int_map jarg1_);
  public final static native void Point_set_3_Int_map_clone__SWIG_1(long jarg1, Point_set_3_Int_map jarg1_, long jarg2, Point_set_3_Int_map jarg2_);
  public final static native void delete_Point_set_3_Int_map(long jarg1);
  public final static native long new_Point_set_3_Float_map();
  public final static native double Point_set_3_Float_map_get(long jarg1, Point_set_3_Float_map jarg1_, int jarg2);
  public final static native void Point_set_3_Float_map_set(long jarg1, Point_set_3_Float_map jarg1_, int jarg2, double jarg3);
  public final static native boolean Point_set_3_Float_map_is_valid(long jarg1, Point_set_3_Float_map jarg1_);
  public final static native long Point_set_3_Float_map_clone__SWIG_0(long jarg1, Point_set_3_Float_map jarg1_);
  public final static native void Point_set_3_Float_map_clone__SWIG_1(long jarg1, Point_set_3_Float_map jarg1_, long jarg2, Point_set_3_Float_map jarg2_);
  public final static native void delete_Point_set_3_Float_map(long jarg1);
}
