/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Point_set_3;
import CGAL.Kernel.Point_3; import CGAL.Kernel.Vector_3; 
public class Point_set_3 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Point_set_3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point_set_3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Point_set_3JNI.delete_Point_set_3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point_set_3(boolean with_normal_map) {
    this(CGAL_Point_set_3JNI.new_Point_set_3__SWIG_0(with_normal_map), true);
  }

  public Point_set_3() {
    this(CGAL_Point_set_3JNI.new_Point_set_3__SWIG_1(), true);
  }

  public Point_set_3(String file) {
    this(CGAL_Point_set_3JNI.new_Point_set_3__SWIG_2(file), true);
  }

  public boolean is_empty() {
    return CGAL_Point_set_3JNI.Point_set_3_is_empty(swigCPtr, this);
  }

  public boolean empty() {
    return CGAL_Point_set_3JNI.Point_set_3_empty(swigCPtr, this);
  }

  public int number_of_points() {
    return CGAL_Point_set_3JNI.Point_set_3_number_of_points(swigCPtr, this);
  }

  public int size() {
    return CGAL_Point_set_3JNI.Point_set_3_size(swigCPtr, this);
  }

  public boolean join(Point_set_3 other) {
    return CGAL_Point_set_3JNI.Point_set_3_join(swigCPtr, this, Point_set_3.getCPtr(other), other);
  }

  public void clear() {
    CGAL_Point_set_3JNI.Point_set_3_clear(swigCPtr, this);
  }

  public void clear_properties() {
    CGAL_Point_set_3JNI.Point_set_3_clear_properties(swigCPtr, this);
  }

  public void reserve(int c) {
    CGAL_Point_set_3JNI.Point_set_3_reserve(swigCPtr, this, c);
  }

  public void resize(int c) {
    CGAL_Point_set_3JNI.Point_set_3_resize(swigCPtr, this, c);
  }

  public int insert() {
    return CGAL_Point_set_3JNI.Point_set_3_insert__SWIG_0(swigCPtr, this);
  }

  public int insert(Point_3 point) {
    return CGAL_Point_set_3JNI.Point_set_3_insert__SWIG_1(swigCPtr, this, Point_3.getCPtr(point), point);
  }

  public int insert(Point_3 point, Vector_3 normal) {
    return CGAL_Point_set_3JNI.Point_set_3_insert__SWIG_2(swigCPtr, this, Point_3.getCPtr(point), point, Vector_3.getCPtr(normal), normal);
  }

  public int insert(Point_set_3 other, int idx) {
    return CGAL_Point_set_3JNI.Point_set_3_insert__SWIG_3(swigCPtr, this, Point_set_3.getCPtr(other), other, idx);
  }

  public void insert_range(double[] range) {
    CGAL_Point_set_3JNI.Point_set_3_insert_range(swigCPtr, this, range);
  }

  public Point_set_3_iterator indices() {
    return new Point_set_3_iterator(CGAL_Point_set_3JNI.Point_set_3_indices(swigCPtr, this), true);
  }

  public Point_3 point(int c) {
    return new Point_3(CGAL_Point_set_3JNI.Point_set_3_point(swigCPtr, this, c), true);
  }

  public Vector_3 normal(int c) {
    return new Vector_3(CGAL_Point_set_3JNI.Point_set_3_normal(swigCPtr, this, c), true);
  }

  public void remove(int c) {
    CGAL_Point_set_3JNI.Point_set_3_remove(swigCPtr, this, c);
  }

  public boolean is_removed(int c) {
    return CGAL_Point_set_3JNI.Point_set_3_is_removed(swigCPtr, this, c);
  }

  public Point_set_3_iterator garbage() {
    return new Point_set_3_iterator(CGAL_Point_set_3JNI.Point_set_3_garbage(swigCPtr, this), true);
  }

  public int number_of_removed_points() {
    return CGAL_Point_set_3JNI.Point_set_3_number_of_removed_points(swigCPtr, this);
  }

  public int garbage_size() {
    return CGAL_Point_set_3JNI.Point_set_3_garbage_size(swigCPtr, this);
  }

  public boolean has_garbage() {
    return CGAL_Point_set_3JNI.Point_set_3_has_garbage(swigCPtr, this);
  }

  public void collect_garbage() {
    CGAL_Point_set_3JNI.Point_set_3_collect_garbage(swigCPtr, this);
  }

  public void cancel_removals() {
    CGAL_Point_set_3JNI.Point_set_3_cancel_removals(swigCPtr, this);
  }

  public boolean has_int_map(String name) {
    return CGAL_Point_set_3JNI.Point_set_3_has_int_map(swigCPtr, this, name);
  }

  public Point_set_3_Int_map add_int_map(String name, int default_value) {
    return new Point_set_3_Int_map(CGAL_Point_set_3JNI.Point_set_3_add_int_map__SWIG_0(swigCPtr, this, name, default_value), true);
  }

  public Point_set_3_Int_map add_int_map(String name) {
    return new Point_set_3_Int_map(CGAL_Point_set_3JNI.Point_set_3_add_int_map__SWIG_1(swigCPtr, this, name), true);
  }

  public Point_set_3_Int_map int_map(String name) {
    return new Point_set_3_Int_map(CGAL_Point_set_3JNI.Point_set_3_int_map(swigCPtr, this, name), true);
  }

  public boolean remove_int_map(Point_set_3_Int_map map) {
    return CGAL_Point_set_3JNI.Point_set_3_remove_int_map(swigCPtr, this, Point_set_3_Int_map.getCPtr(map), map);
  }

  public boolean has_float_map(String name) {
    return CGAL_Point_set_3JNI.Point_set_3_has_float_map(swigCPtr, this, name);
  }

  public Point_set_3_Float_map add_float_map(String name, double default_value) {
    return new Point_set_3_Float_map(CGAL_Point_set_3JNI.Point_set_3_add_float_map__SWIG_0(swigCPtr, this, name, default_value), true);
  }

  public Point_set_3_Float_map add_float_map(String name) {
    return new Point_set_3_Float_map(CGAL_Point_set_3JNI.Point_set_3_add_float_map__SWIG_1(swigCPtr, this, name), true);
  }

  public Point_set_3_Float_map float_map(String name) {
    return new Point_set_3_Float_map(CGAL_Point_set_3JNI.Point_set_3_float_map(swigCPtr, this, name), true);
  }

  public boolean remove_float_map(Point_set_3_Float_map map) {
    return CGAL_Point_set_3JNI.Point_set_3_remove_float_map(swigCPtr, this, Point_set_3_Float_map.getCPtr(map), map);
  }

  public boolean has_normal_map() {
    return CGAL_Point_set_3JNI.Point_set_3_has_normal_map(swigCPtr, this);
  }

  public Point_set_3_Vector_map add_normal_map() {
    return new Point_set_3_Vector_map(CGAL_Point_set_3JNI.Point_set_3_add_normal_map(swigCPtr, this), true);
  }

  public Point_set_3_Vector_map normal_map() {
    return new Point_set_3_Vector_map(CGAL_Point_set_3JNI.Point_set_3_normal_map(swigCPtr, this), true);
  }

  public boolean remove_normal_map() {
    return CGAL_Point_set_3JNI.Point_set_3_remove_normal_map(swigCPtr, this);
  }

  public Point_set_3_Point_map point_map() {
    return new Point_set_3_Point_map(CGAL_Point_set_3JNI.Point_set_3_point_map(swigCPtr, this), true);
  }

  public void copy_properties(Point_set_3 other) {
    CGAL_Point_set_3JNI.Point_set_3_copy_properties(swigCPtr, this, Point_set_3.getCPtr(other), other);
  }

  public String[] properties() {return CGAL_Point_set_3JNI.Point_set_3_properties(swigCPtr, this);}

  public String info() {
    return CGAL_Point_set_3JNI.Point_set_3_info(swigCPtr, this);
  }

  public Point_set_3_Int_iterator range(Point_set_3_Int_map map) {
    return new Point_set_3_Int_iterator(CGAL_Point_set_3JNI.Point_set_3_range__SWIG_0(swigCPtr, this, Point_set_3_Int_map.getCPtr(map), map), true);
  }

  public Point_set_3_Float_iterator range(Point_set_3_Float_map map) {
    return new Point_set_3_Float_iterator(CGAL_Point_set_3JNI.Point_set_3_range__SWIG_1(swigCPtr, this, Point_set_3_Float_map.getCPtr(map), map), true);
  }

  public Point_set_3_Point_iterator points() {
    return new Point_set_3_Point_iterator(CGAL_Point_set_3JNI.Point_set_3_points(swigCPtr, this), true);
  }

  public Point_set_3_Vector_iterator normals() {
    return new Point_set_3_Vector_iterator(CGAL_Point_set_3JNI.Point_set_3_normals(swigCPtr, this), true);
  }

  public void read(String file) {
    CGAL_Point_set_3JNI.Point_set_3_read(swigCPtr, this, file);
  }

  public boolean write(String file) {
    return CGAL_Point_set_3JNI.Point_set_3_write(swigCPtr, this, file);
  }

}
