/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Point_set_3;

  import java.lang.Iterable;
  import java.lang.UnsupportedOperationException;
  import java.util.Iterator;
  
public class Point_set_3_Int_iterator implements   Iterable<Integer>, Iterator<Integer>  {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Point_set_3_Int_iterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point_set_3_Int_iterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Point_set_3JNI.delete_Point_set_3_Int_iterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

    public void remove() {
      throw new UnsupportedOperationException();
    }
    
    public Iterator<Integer> iterator() {
      return this;
    }

    public Integer next() {
      return slow_next();
    }
  
  public Point_set_3_Int_iterator() {
    this(CGAL_Point_set_3JNI.new_Point_set_3_Int_iterator(), true);
  }

  public Integer slow_next() {
    return CGAL_Point_set_3JNI.Point_set_3_Int_iterator_slow_next(swigCPtr, this);
  }

  public void next(SWIGTYPE_p_int r) {
    CGAL_Point_set_3JNI.Point_set_3_Int_iterator_next(swigCPtr, this, SWIGTYPE_p_int.getCPtr(r));
  }

  public Point_set_3_Int_iterator clone() {
    return new Point_set_3_Int_iterator(CGAL_Point_set_3JNI.Point_set_3_Int_iterator_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Point_set_3_Int_iterator other) {
    CGAL_Point_set_3JNI.Point_set_3_Int_iterator_clone__SWIG_1(swigCPtr, this, Point_set_3_Int_iterator.getCPtr(other), other);
  }

  public boolean hasNext() {
    return CGAL_Point_set_3JNI.Point_set_3_Int_iterator_hasNext(swigCPtr, this);
  }

  public boolean equals(Point_set_3_Int_iterator p) {
    return CGAL_Point_set_3JNI.Point_set_3_Int_iterator_equals(swigCPtr, this, Point_set_3_Int_iterator.getCPtr(p), p);
  }

  public boolean not_equals(Point_set_3_Int_iterator p) {
    return CGAL_Point_set_3JNI.Point_set_3_Int_iterator_not_equals(swigCPtr, this, Point_set_3_Int_iterator.getCPtr(p), p);
  }

}
