/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Point_set_3;

  import CGAL.Kernel.Point_3;
  import java.lang.Iterable;
  import java.lang.UnsupportedOperationException;
  import java.util.Iterator;
  
public class Point_set_3_Point_iterator implements   Iterable<Point_3>, Iterator<Point_3>  {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Point_set_3_Point_iterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point_set_3_Point_iterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Point_set_3JNI.delete_Point_set_3_Point_iterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

    public void remove() {
      throw new UnsupportedOperationException();
    }
    
    public Iterator<Point_3> iterator() {
      return this;
    }
    
    //we store an object of type Point_3 to avoid
    //creation and allocation of a java object at each iteration.
    private Point_3 objectInstance = new Point_3();
    public Point_3 next() {
      next(objectInstance);
      return objectInstance;
    }
  
  public Point_set_3_Point_iterator() {
    this(CGAL_Point_set_3JNI.new_Point_set_3_Point_iterator(), true);
  }

  public Point_3 slow_next() {
    return new Point_3(CGAL_Point_set_3JNI.Point_set_3_Point_iterator_slow_next(swigCPtr, this), true);
  }

  public void next(Point_3 r) {
    CGAL_Point_set_3JNI.Point_set_3_Point_iterator_next(swigCPtr, this, Point_3.getCPtr(r), r);
  }

  public Point_set_3_Point_iterator clone() {
    return new Point_set_3_Point_iterator(CGAL_Point_set_3JNI.Point_set_3_Point_iterator_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Point_set_3_Point_iterator other) {
    CGAL_Point_set_3JNI.Point_set_3_Point_iterator_clone__SWIG_1(swigCPtr, this, Point_set_3_Point_iterator.getCPtr(other), other);
  }

  public boolean hasNext() {
    return CGAL_Point_set_3JNI.Point_set_3_Point_iterator_hasNext(swigCPtr, this);
  }

  public boolean equals(Point_set_3_Point_iterator p) {
    return CGAL_Point_set_3JNI.Point_set_3_Point_iterator_equals(swigCPtr, this, Point_set_3_Point_iterator.getCPtr(p), p);
  }

  public boolean not_equals(Point_set_3_Point_iterator p) {
    return CGAL_Point_set_3JNI.Point_set_3_Point_iterator_not_equals(swigCPtr, this, Point_set_3_Point_iterator.getCPtr(p), p);
  }

}
